### ISSUE TITLE
Store stockpile priority

### ISSUE THREAD

**Issue by LockdownX7** [KiameV/rimworld-SaveStorageSettings#11]
Would be really handy if a stockpile's priority level was included in the saved data.

Thanks for the amazing QoL mod!

**Comment by KiameV** [comment]
I do remember debating whether to include priority and I remember two thoughts that made me decide not to include the priority:
1. The user loads different settings on the same stockpile. In this case it would be frustrating to have to remember to set the priority again (if it was different)
2. A user might have more than one storage where they have the same settings applied. In this case they'll have to set the priority anyway.

Personally I do not always have the same priority for each zone each game as well.

Based off those considerations I decided it was better that the user control priority each game/each stockpile.

If I come back to this mod I will consider adding a setting for this. As of now I don't think i'm going to do anything.

Thank you for the recommendation.

Feel free to add any additional comments if you'd like.
