### ISSUE TITLE
Allow Building_Storage that aren't "shelf"

### ISSUE THREAD

**Issue by lilwhitemouse** [KiameV/rimworld-SaveStorageSettings#12]
Hey, LWM here.  I got a request to add support for this mod to Deep Storage (https://github.com/lilwhitemouse/RimWorld-LWM.DeepStorage/issues/37) over on Steam.  I looked through your code, and it looks like a simple change your end would take care of adding all the buildings I add in.

In HarmonyPatches.cs, you check the defName=="shelf" and go from there.  Is it possible to just add it to all Buildings_Storage, just using the defName in place of "shelf"?  That seems to be what your utility does anyway.  Is that a possible change on your end?  Would it cause other unintended problems?

(I also note your utility would add all ...7? 8? of my buildings to the same storageTypeName...does that even matter?)

If I can help, give a shout.

**Comment by tofluid** [comment]
All storage types should now be supported

**Comment by KiameV** [comment]
All storage types should now be supported. I've also added a way to specify what type of storage it is via xml patching.

**Comment by KiameV** [comment]
Example of xml patch: https://github.com/KiameV/rimworld-changedresser/blob/master/1.3/Patches/SaveStorageSettings.xml

```
<?xml version="1.0" encoding="utf-8" ?>
<Patch>
	<Operation Class="PatchOperationFindMod">
		<mods>
			<li>[KV] Save Storage, Outfit, Crafting, Drug, &amp; Operation Settings</li>
		</mods>
		<match Class="PatchOperationAdd">
			<xpath>/Defs/ThingDef[defName="ChangeDresser"]/comps</xpath>
			<value>
				<li Class="SaveStorageSettings.CompProperties_SaveStorageSettings">
					<name>Apparel_Management</name>
				</li>
			</value>
		</match>
	</Operation>
</Patch>
```
