### ISSUE TITLE
Can't save load settings

### ISSUE THREAD

**Issue by bananasss00** [KiameV/rimworld-SaveStorageSettings#3]
**In FileListDialog.cs::ReloadFiles()  Path.Combine redundant?**

```
protected void ReloadFiles()
{
	string path;
	IOUtil.TryGetDirectoryPath(this.StorageTypeName, out path);

	this.files.Clear();
	foreach (string file in Directory.GetFiles(path))
	{
		try
		{
			Log.Warning($"Combine {path} +++ {file}");
			this.files.Add(new FileInfo(/*Path.Combine(path, */file/*)*/));
		}
		catch (Exception ex)
		{
			Log.Error("Exception reloading " + file + ": " + ex.ToString());
		}
	}
}
```

**because ingame i'm get path**
Combine _Configs\SaveStorageSettings/Zone_Stockpile +++ _Configs\SaveStorageSettings/Zone_Stockpile\my_save_file.txt

**Comment by bananasss00** [comment]
PS: I'm use launch option RW -savedatafolder=_Configs

**Comment by KiameV** [comment]
Hmm i'll take a look and see if i'm using single \ anywhere. I'll see if i can spin up a linux vm somewhere and test it out

**Comment by bananasss00** [comment]
this.files.Add(new FileInfo(file));

this work for me, without problems

PS:
Directory.GetFiles(path) return full path to files or relative path if initial 'path' was relative

**Comment by KiameV** [comment]
Should be fixed now
