### ISSUE TITLE
Load Settings doesn't work with custom config folders

### ISSUE THREAD

**Issue by LockdownX7** [KiameV/rimworld-SaveStorageSettings#6]
If RimWorld is using the -savedatafolder launch parameter to specify a custom folder outside of AppData, this mod will be able to save settings and I can see the files popping up in MyConfigFolder\SaveStorageSettings\, but nothing will happen if I try to load a setting into a stockpile/outfit/etc. As far as I'm aware, the mod should have both read and write access to the custom folder, as all other mods can load/save data into it just fine.

As a temporary workaround, I've moved my custom config folder into AppData, next to RimWorld's default location, and that allowed the mod to work as intended. I assume the loading process is hardcoded to target \AppData\LocalLow\Ludeon Studios\ as the root, whereas the save process is correctly targeting custom save folders.

RW version is 1.0.2150 64-bit, on Windows 10. No console errors or warnings are generated when attempting to load a setting, simply nothing happens.

**Comment by KiameV** [comment]
Should be fixed now
